/* Let’s Talk: verified contact channels and a mailto-based signal form until a backend inbox is connected. */
import { useState } from "react";
import { ArrowUpRight } from "lucide-react";
const contactLinks = [
  { label: "EMAIL", value: "haripriyaatwork@gmail.com", href: "mailto:haripriyaatwork@gmail.com" },
  { label: "LINKEDIN", value: "Haripriya Mishra", href: "https://www.linkedin.com/in/haripriyamishra2301/" },
  { label: "SUBSTACK", value: "@haripriyamishra", href: "https://substack.com/@haripriyamishra?utm_source=user-menu" },
  { label: "INSTAGRAM", value: "@fromthepoetess", href: "https://www.instagram.com/fromthepoetess/" },
];
export default function Connect() { const [sent, setSent] = useState(false); const handleSubmit = (e: React.FormEvent<HTMLFormElement>) => { e.preventDefault(); const form = new FormData(e.currentTarget); const subject = `Portfolio enquiry from ${String(form.get("name") || "a visitor")}`; const body = `Name: ${String(form.get("name") || "")}\nEmail: ${String(form.get("email") || "")}\n\n${String(form.get("message") || "")}`; window.location.href = `mailto:haripriyaatwork@gmail.com?subject=${encodeURIComponent(subject)}&body=${encodeURIComponent(body)}`; setSent(true); }; return <section className="page container connect-page"><div className="page-intro"><span className="eyebrow">Let’s Talk</span><h1>LET’S<br /><em>TALK.</em></h1><p>For work. For ideas. For research. For writing. For something I haven’t thought of yet.</p></div><div className="connect-grid"><div className="connect-links"><span className="eyebrow">Find me where the links are</span><div className="contact-link-list">{contactLinks.map((link) => <a className="contact-link" href={link.href} target={link.href.startsWith("mailto:") ? undefined : "_blank"} rel={link.href.startsWith("mailto:") ? undefined : "noreferrer"} key={link.label}><span className="project-number">{link.label}</span><strong>{link.value}</strong><ArrowUpRight size={15} /></a>)}</div></div><form className="connect-form" onSubmit={handleSubmit}><span className="eyebrow">Start a thread</span><label>Name<input name="name" required placeholder="Your name" /></label><label>Email<input name="email" required type="email" placeholder="you@example.com" /></label><label>What’s on your mind?<textarea name="message" required rows={5} placeholder="A brief, an idea, a question..." /></label><button className="button button-rose" type="submit">{sent ? "Email app opened" : "Send the signal"} <ArrowUpRight size={15} /></button>{sent && <p className="form-success">Your message is ready to send to <strong>haripriyaatwork@gmail.com</strong>. Your email app should now be open with the message filled in.</p>}</form></div></section>; }
