/* Home: editorial archive opening with a philosophical statement, identity orbit, and range-first spectrum. */
import { useState } from "react";
import { Link } from "wouter";
import { ArrowDownRight, ArrowUpRight } from "lucide-react";
import { EmptyState } from "../App";
const identities = ["COMMUNICATOR", "WRITER", "RESEARCHER", "STRATEGIST", "JOURNALIST", "CREATOR", "STUDENT", "POET", "STORYTELLER"];
const skills = { STRATEGY: ["Communication Strategy", "Brand Strategy", "Content Strategy", "Campaign Strategy", "Brand Positioning"], WRITING: ["Social Media Writing", "Copywriting", "Journalism", "Website Copy", "SEO", "AEO", "LinkedIn", "Long-form Writing", "Poetry"], CREATIVE: ["Graphic Design", "Video Editing", "Presentation Design", "Content Creation"], DIGITAL: ["Social Media Management", "Digital Marketing", "Performance Marketing", "Community Management"], PEOPLE: ["Client Management", "Account Handling", "Team Coordination", "Creative Coordination"] };
export default function Home() { const [identity, setIdentity] = useState(identities[0]); const [category, setCategory] = useState("STRATEGY"); return <>
  <section className="home-hero container"><div className="hero-kicker"><span className="signal-cross">+</span> Personal archive / work in progress</div><div className="hero-statement"><span className="eyebrow">The central idea</span><h1>Jack of all trades,<br /><em>master of none,</em></h1><p className="hero-quote">but oftentimes better than a master of one.</p><p className="hero-note">My career hasn’t been a straight line.<br />It’s been more of a spectrum.</p></div><div className="identity-stage"><div className="orbit orbit-one" /><div className="orbit orbit-two" /><div className="portrait-cutout"><img src="/manus-storage/haripriya-portrait-alpha_6db75f0e.png" alt="Haripriya Mishra" /></div>{identities.map((item, i) => <button key={item} className={`orbit-label orbit-${i + 1} ${identity === item ? "selected" : ""}`} onClick={() => setIdentity(item)}>{item}</button>)}</div><div className="hero-name"><span className="eyebrow">Haripriya Mishra</span><h2>Communicator · Writer · Researcher · Strategist · Creator</h2><Link href="/who-i-am" className="text-link">Who I am <ArrowUpRight size={15} /></Link></div></section>
  <section className="spectrum-band"><div className="container"><div className="section-heading"><div><span className="eyebrow">01 / The spectrum</span><h2>A plethora<br /><em>of interests.</em></h2></div><p>In communication, there isn’t much I don’t want to do.</p></div><div className="skill-tabs">{Object.keys(skills).map((item) => <button className={category === item ? "skill-tab active" : "skill-tab"} onClick={() => setCategory(item)} key={item}>{item}</button>)}</div><div className="skill-cloud">{skills[category as keyof typeof skills].map((item) => <span key={item}>{item}</span>)}</div></div></section>
  <section className="home-archive container"><div className="section-heading"><div><span className="eyebrow">02 / The archive</span><h2>Things I’m<br /><em>making room for.</em></h2></div><Link href="/work" className="text-link">Open work archive <ArrowUpRight size={15} /></Link></div><div className="archive-teasers"><Link href="/work" className="archive-teaser"><span>WRITING</span><strong>Articles, essays, journalism, poetry</strong><ArrowDownRight size={19} /></Link><Link href="/thinking" className="archive-teaser"><span>THINKING</span><strong>Opinions, observations, unfinished thoughts</strong><ArrowDownRight size={19} /></Link><Link href="/results" className="archive-teaser"><span>PROOF</span><strong>The numbers part, eventually</strong><ArrowDownRight size={19} /></Link></div></section>
  <section className="home-quote"><div className="container"><span className="signal-cross">+</span><p>“The portfolio is not the product.<br /><em>The person behind the portfolio is.</em>”</p></div></section>
</>; }
