import { useState } from "react";
import { ArrowUpRight, Download } from "lucide-react";

const stops = [
  { label: "SCIENCE TUTOR", role: "Science Tutor", company: "InPHinity Education", date: "Jan 2023 – Mar 2024", location: "Vadodara", description: "Conducted science classes for primary students and simplified complex concepts through activity-based learning.", skills: "Communication · Leadership · Lesson planning" },
  { label: "INPAC TIMES", role: "Journalism Intern", company: "INPAC Times", date: "May 2023 – Jun 2023", location: "Remote", description: "Reported on geopolitics, national affairs, crime, and entertainment, while applying SEO practices to improve article discoverability.", skills: "Reporting · SEO · National affairs" },
  { label: "SPORTSKEEDA", role: "Reality TV Writer", company: "Sportskeeda", date: "Aug 2023 – Oct 2023", location: "Remote", description: "Produced SEO-driven articles on American reality television and entertainment within strict editorial deadlines, working closely with editors to maximise engagement and search performance.", skills: "SEO writing · Editorial deadlines · Entertainment" },
  { label: "ARCLANTIC", role: "Journalist Intern", company: "Arclantic", date: "Jan 2025 – Mar 2025", location: "Remote", description: "Wrote analytical articles covering politics, world affairs, lifestyle, entertainment, and social issues. Covered live events and election-related developments while collaborating with editors on factual accuracy and storytelling.", skills: "Journalism · Research · Factual accuracy" },
  { label: "KAAFILA", role: "Communication Head", company: "Faculty of Journalism & Communication, MSU", date: "Jan 2025 – Mar 2025", location: "Vadodara", description: "Led the communications team for the university cultural festival, planned publicity campaigns, coordinated with media partners and stakeholders, and prepared sponsorship reports and post-event documentation.", skills: "Communication strategy · Publicity · Stakeholders" },
  { label: "ADWISE", role: "Social Media Manager Intern", company: "Adwise", date: "Mar 2025 – Jun 2025", location: "Vadodara", description: "Developed social media strategy for a premium menswear brand, conducted competitor and market research, created captions, reel scripts, carousel content and campaign copy, and coordinated client approvals.", skills: "Social strategy · Brand positioning · Copywriting" },
  { label: "BUZZ UP / PART-TIME", role: "Social Media Executive & Junior Content Writer", company: "Buzz Up Marketing", date: "Earlier role · before promotion", location: "Vadodara", description: "Started with Buzz Up Marketing in a part-time social media and junior content writing role before progressing into full-time account management.", skills: "Social media · Content writing · Client coordination" },
  { label: "BUZZ UP / ACCOUNT MANAGER", role: "Account Manager · Full-Time", company: "Buzz Up Marketing", date: "Jul 2025 – Present", location: "Vadodara", description: "Manage communication and digital marketing strategies for 10+ client accounts across diverse industries. Lead discovery calls, strategic planning, stakeholder communication, brand positioning, messaging, founder branding, integrated campaigns, website copy, SEO articles, newsletters, presentations, and cross-functional delivery.", skills: "Account management · Brand strategy · Digital campaigns" },
];

const skillGroups = [
  { title: "Strategy & Brand", skills: ["Brand Strategy & Positioning", "Communication Strategy", "Digital Marketing", "Account Management", "LinkedIn Personal Branding", "Founder Branding", "Content Strategy", "Campaign Planning"] },
  { title: "Content & Communication", skills: ["Client Communication", "Website Copywriting", "SEO Content Writing", "SEO Optimization", "Community Management"] },
  { title: "Creative & Production", skills: ["Canva & Creative Design", "Video Editing", "Canva", "AI-assisted Marketing"] },
  { title: "Platforms & Analytics", skills: ["Meta Business Suite", "Google Analytics", "Google Search Console", "LinkedIn Analytics", "Instagram Insights", "X Analytics", "Grammarly", "AI Tools (ChatGPT, Gemini, Claude, Perplexity)", "Microsoft Office", "Google Workspace"] },
  { title: "Professional Strengths", skills: ["Strategic Thinking", "Leadership", "Critical Thinking", "Project Management", "Collaboration", "Time Management", "Adaptability"] },
  { title: "Languages", skills: ["English (Professional)", "Hindi (Native)", "Gujarati (Native)"] },
];

export default function Resume() {
  const [selected, setSelected] = useState(stops.length - 1);
  const current = stops[selected];
  return <section className="page container resume-page">
    <div className="page-intro"><span className="eyebrow">06 / Proof</span><h1>If you insist on a<br /><em>résumé, fine.</em></h1><p>For those who prefer things in chronological order. Here is the factual version.</p><a className="button button-rose resume-download-top" href="/manus-storage/haripriya-mishra-resume_13ec6384.pdf" target="_blank" rel="noreferrer"><Download size={15} /> Open resume PDF</a></div>
    <div className="resume-contact"><div><strong>Haripriya Mishra</strong><span>Communication Strategist | Brand Marketing | Content & Digital Communications</span></div><div><span>Vadodara, Gujarat</span><span>Haripriyaatwork@gmail.com</span></div></div>
    <section className="resume-summary"><span className="eyebrow">Summary</span><p>Communication and Brand Marketing professional with experience developing communication strategies, digital campaigns, and brand positioning for B2B, B2C, D2C, and founder-led businesses. Skilled in client management, account handling, content strategy, LinkedIn marketing, website communication, SEO copywriting, and integrated marketing campaigns.</p></section>
    <div className="career-map"><div className="section-heading"><div><span className="eyebrow">Career trajectory</span><h2>Not a straight<br /><em>line.</em></h2></div><p>A chronological record of roles, reporting, communication, and progression. Select a role to read the detail.</p></div><div className="trajectory-timeline"><div className="trajectory-track"><span className="trajectory-line" aria-hidden="true" />{stops.map((item, i) => <button aria-label={`Open ${item.role} at ${item.company}`} className={`timeline-stop ${selected === i ? "active" : ""}`} onClick={() => setSelected(i)} key={`${item.label}-${item.date}`}><span className="timeline-dot" aria-hidden="true" /><span className="timeline-label"><small>{String(i + 1).padStart(2, "0")} · {item.date}</small><strong>{item.role}</strong><em>{item.company}</em></span></button>)}</div></div><div className="stop-detail verified-detail"><div><span className="eyebrow">Selected role / {current.label}</span><h3>{current.role}</h3><strong>{current.company}</strong><span>{current.date} · {current.location}</span></div><p>{current.description}</p><small>{current.skills}</small></div></div>
    <section className="experience-section"><span className="eyebrow">Experience</span>{stops.slice().reverse().map((item) => <article className="experience-row" key={`${item.label}-${item.date}`}><div><strong>{item.role}</strong><span>{item.company}</span></div><span>{item.date}</span><p>{item.description}</p></article>)}</section>
    <section className="education-section"><span className="eyebrow">Education</span><div className="education-grid"><article><strong>Master of Journalism & Mass Communication</strong><span>Faculty of Journalism & Communication, The Maharaja Sayajirao University of Baroda</span><small>2024 – 2026 · CGPA: 7.30/10</small></article><article><strong>Bachelor of Arts (Honours), Archaeology & Ancient History</strong><span>The Maharaja Sayajirao University of Baroda</span><small>2021 – 2024</small></article><article><strong>Higher Secondary (HSC)</strong><span>Narayan Vidyalaya, Vadodara</span><small>2021 · 75.57%</small></article><article><strong>Secondary School (SSC)</strong><span>Shree Kavant English High School</span><small>2019 · 72%</small></article></div></section>
    <section className="skills-section"><span className="eyebrow">Skills</span><div className="resume-skill-groups">{skillGroups.map((group) => <article className="resume-skill-group" key={group.title}><span className="project-number">{group.title}</span><div>{group.skills.map((skill) => <span key={skill}>{skill}</span>)}</div></article>)}</div></section>
    <section className="projects-section resume-strategy-link"><span className="eyebrow">Strategy archive</span><div className="resume-strategy-link-content"><div><h2>Content, Strategy & Direction</h2><p>The strategy work is documented in the Work archive, with each entry opening into its own context and approach.</p></div><a className="text-link" href="/work#strategy">View strategy work <ArrowUpRight size={15} /></a></div></section>
    <div className="resume-download"><a className="button button-rose" href="/manus-storage/haripriya-mishra-resume_13ec6384.pdf" download><Download size={15} /> Download resume PDF</a></div>
  </section>;
}

/* Editorial Signal reminder: this page uses a chronological, evidence-first trajectory with black structure, restrained pink accents, and legible role separation. */
