/* Resume: all facts below come from the supplied resume source; the PDF is the generated downloadable version of that source. */
import { useState } from "react";
import { ArrowDown, ArrowUpRight, Download } from "lucide-react";

const stops = [
  { label: "SCIENCE TUTOR", role: "Science Tutor", company: "InPHinity Education", date: "Jan 2023 – Mar 2024", location: "Vadodara", description: "Conducted science classes for primary students and simplified complex concepts through activity-based learning.", skills: "Communication · Leadership · Lesson planning" },
  { label: "JOURNALISM", role: "Journalism Intern", company: "INPAC Times", date: "May 2023 – Jun 2023", location: "Remote", description: "Reported on geopolitics, national affairs, crime, and entertainment while applying SEO practices to improve discoverability.", skills: "Reporting · SEO · National affairs" },
  { label: "REALITY TV", role: "Reality TV Writer", company: "Sportskeeda", date: "Aug 2023 – Oct 2023", location: "Remote", description: "Produced SEO-driven articles on American reality television and entertainment within strict editorial deadlines.", skills: "SEO writing · Editorial deadlines · Entertainment" },
  { label: "ARCHAEOLOGY", role: "Bachelor of Arts (Honours), Archaeology & Ancient History", company: "The Maharaja Sayajirao University of Baroda", date: "2021 – 2024", location: "Vadodara", description: "Undergraduate study in Archaeology & Ancient History.", skills: "Academic research · History" },
  { label: "ARCLANTIC", role: "Journalist Intern", company: "Arclantic", date: "Jan 2025 – Mar 2025", location: "Remote", description: "Wrote analytical articles covering politics, world affairs, lifestyle, entertainment, and social issues; covered live events and election-related developments.", skills: "Journalism · Research · Factual accuracy" },
  { label: "KAAFILA", role: "Communication Head", company: "Faculty of Journalism & Communication, MSU", date: "Jan 2025 – Mar 2025", location: "Vadodara", description: "Led the communications team for the university cultural festival, planned publicity campaigns, coordinated media partners, and prepared sponsorship reports.", skills: "Communication strategy · Publicity · Stakeholders" },
  { label: "ADWISE", role: "Social Media Manager Intern", company: "Adwise", date: "Mar 2025 – Jun 2025", location: "Vadodara", description: "Developed social media strategy for a premium menswear brand, conducted competitor research, and created campaign copy and creatives.", skills: "Social strategy · Brand positioning · Copywriting" },
  { label: "BUZZ UP", role: "Social Media Executive & Junior Content Writer", company: "Buzz Up Marketing", date: "Jul 2025 – Present", location: "Vadodara", description: "Manage communication and digital marketing strategies for 10+ client accounts across diverse industries, including positioning, content strategy, founder branding, and integrated campaigns.", skills: "Brand strategy · Digital campaigns · Client management" },
];
const skills = ["Brand Strategy & Positioning", "Communication Strategy", "Digital Marketing", "Account Management", "Client Communication", "LinkedIn Personal Branding", "Founder Branding", "Content Strategy", "Website Copywriting", "SEO Content Writing", "Campaign Planning", "Community Management", "Canva & Creative Design", "Video Editing", "Meta Business Suite", "Google Analytics", "Google Search Console", "LinkedIn Analytics", "Instagram Insights", "X Analytics", "Strategic Thinking", "Leadership", "Critical Thinking", "Project Management", "Collaboration", "Time Management", "Adaptability", "English (Professional)", "Hindi (Native)", "Gujarati (Native)"];

export default function Resume() {
  const [selected, setSelected] = useState(stops.length - 1);
  const current = stops[selected];
  return <section className="page container resume-page">
    <div className="page-intro"><span className="eyebrow">06 / Proof</span><h1>If you insist on a<br /><em>résumé, fine.</em></h1><p>For those who prefer things in chronological order. Here is the factual version.</p><a className="button button-rose resume-download-top" href="/manus-storage/haripriya-mishra-resume_13ec6384.pdf" target="_blank" rel="noreferrer"><Download size={15} /> Open resume PDF</a></div>
    <div className="resume-contact"><div><strong>Haripriya Mishra</strong><span>Communication Strategist | Brand Marketing | Content & Digital Communications</span></div><div><span>Vadodara, Gujarat</span><span>(+91) 7874585372</span><span>Haripriyaatwork@gmail.com</span></div></div>
    <section className="resume-summary"><span className="eyebrow">Summary</span><p>Communication and Brand Marketing professional with experience developing communication strategies, digital campaigns, and brand positioning for B2B, B2C, D2C, and founder-led businesses. Skilled in client management, account handling, content strategy, LinkedIn marketing, website communication, SEO copywriting, and integrated marketing campaigns.</p></section>
    <div className="career-map"><div className="section-heading"><div><span className="eyebrow">Career trajectory map</span><h2>Not a straight<br /><em>line.</em></h2></div><p>Verified stops from the supplied resume. Click a stop to open the detail.</p></div><div className="route verified-route"><div className="route-line" />{stops.map((item, i) => <button aria-label={`Open ${item.role} at ${item.company}`} className={`route-stop stop-${i} ${selected === i ? "active" : ""}`} onClick={() => setSelected(i)} key={item.label}><i />{item.label}</button>)}</div><div className="stop-detail verified-detail"><div><span className="eyebrow">Selected stop / {current.label}</span><h3>{current.role}</h3><strong>{current.company}</strong><span>{current.date} · {current.location}</span></div><p>{current.description}</p><small>{current.skills}</small></div></div>
    <section className="experience-section"><span className="eyebrow">Experience</span>{stops.filter((s) => !["ARCHAEOLOGY"].includes(s.label)).slice().reverse().map((item) => <article className="experience-row" key={item.label}><div><strong>{item.role}</strong><span>{item.company}</span></div><span>{item.date}</span><p>{item.description}</p></article>)}</section>
    <section className="education-section"><span className="eyebrow">Education</span><div className="education-grid"><article><strong>Master of Journalism & Mass Communication</strong><span>Faculty of Journalism & Communication, The Maharaja Sayajirao University of Baroda</span><small>2024 – 2026 · CGPA: 7.30/10</small></article><article><strong>Bachelor of Arts (Honours), Archaeology & Ancient History</strong><span>The Maharaja Sayajirao University of Baroda</span><small>2021 – 2024</small></article><article><strong>Higher Secondary (HSC)</strong><span>Narayan Vidyalaya, Vadodara</span><small>2021 · 75.57%</small></article><article><strong>Secondary School (SSC)</strong><span>Shree Kavant English High School</span><small>2019 · 72%</small></article></div></section>
    <section className="skills-section"><span className="eyebrow">Skills</span><div className="skill-cloud">{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></section>
    <section className="projects-section"><span className="eyebrow">Selected projects</span><div className="project-proof-grid"><article><strong>10+ B2B and D2C clients</strong><p>End-to-end communication strategy across manufacturing, fintech, sustainability, and life sciences, delivering 10+ lakh impressions and 6+ lakh views.</p></article><article><strong>Kaafila</strong><p>Communication strategy for MSU’s university-wide cultural festival, including media partnerships and stakeholder communication.</p></article><article><strong>Published journalism</strong><p>Articles published on Sportskeeda, Arclantic, and INPAC Times.</p></article><article><strong>Creative Writing Competition</strong><p>Winner, Kaafila 2024, Faculty of Journalism & Communication, MSU.</p></article></div></section>
    <div className="resume-download"><span>Keep the PDF version nearby.</span><a className="button button-rose" href="/manus-storage/haripriya-mishra-resume_13ec6384.pdf" download><Download size={15} /> Download resume PDF</a></div>
  </section>;
}
