/* Thinking archive: linked posts are verified; future essays and research remain explicit empty states. */
import { ArrowUpRight } from "lucide-react";
import { EmptyState } from "../App";
const sections = ["ESSAYS", "OPINIONS", "RESEARCH", "LINKEDIN WRITING", "SUBSTACK", "POETRY", "COMMUNICATION IDEAS", "OBSERVATIONS", "PERSONAL THINKING"];
const linkedPosts = [
  { title: "Communication is the KEY", note: "Clarity, intent, audience, and the work of making a message land.", impressions: "3,258 impressions", href: "https://www.linkedin.com/posts/haripriyamishra2301_communication-is-the-key-not-just-activity-7421027789933457408-Kzsd" },
  { title: "Pick a niche. I WON’T.", note: "Range is not a lack of focus; it is depth across mediums.", impressions: "2,502 impressions", href: "https://www.linkedin.com/posts/haripriyamishra2301_lie-linkedin-keeps-repeating-pick-a-niche-activity-7406898812314828800-cWP-" },
  { title: "Write a bad prompt", note: "A rough first attempt gives you something to critique and shape.", impressions: "2,502 impressions", href: "https://www.linkedin.com/posts/haripriyamishra2301_my-advice-write-a-bad-prompt-yes-activity-7455818283372638208-MS_P" },
];
export default function Thinking() { return <section className="page container thinking-page"><div className="page-intro"><span className="eyebrow">04 / Exploration</span><h1>THINGS I<br /><em>THINK ABOUT.</em></h1><p>Work is what I make for a brief. Thinking is what stays with me after.</p></div><div className="thinking-grid">{sections.map((section, i) => <article className={i === 3 ? "thinking-card featured" : "thinking-card"} key={section}><span className="project-number">0{i + 1}</span><h2>{section}</h2>{section === "LINKEDIN WRITING" ? <div className="thinking-link-list">{linkedPosts.map((post) => <a className="thinking-link-card" href={post.href} target="_blank" rel="noreferrer" key={post.href}><strong>{post.title}</strong><span>{post.note}</span><small>{post.impressions} <ArrowUpRight size={14} /></small></a>)}</div> : <EmptyState label="WRITING TO BE ADDED" detail="Title, excerpt, date, tags, and link will appear here." />}</article>)}</div><div className="poetry-mode"><span className="eyebrow">A different kind of archive</span><h2>POETRY</h2><p>More intimate. More editorial. More minimal.</p><EmptyState label="POEMS TO BE ADDED" /></div></section>; }
